# Generated by Django 6.0.6 on 2026-06-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_brand_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('A4Tech', 'A4Tech'), ('Ajazz', 'Ajazz'), ('ASUS', 'ASUS'), ('AMD', 'AMD'), ('ATTACK SHARK', 'ATTACK SHARK'), ('Aula', 'Aula'), ('GamePro', 'GamePro'), ('Hator', 'Hator'), ('Intel', 'Intel'), ('Keychron', 'Keychron'), ('Logitech', 'Logitech'), ('NVIDIA', 'NVIDIA'), ('Razer', 'Razer'), ('Real-El', 'Real-El'), ('RZTK', 'RZTK'), ('1STPLAYER', '1STPLAYER')], max_length=100, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('monitors', 'Монітори'), ('processors', 'Процесори'), ('mice', 'Ігрові миші'), ('keyboards', 'Клавіатури'), ('gpu', 'Відеокарти')], max_length=50, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Характеристики / Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Назва предмета'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Ціна (грн)'),
        ),
    ]
