# Generated by Django 6.0.6 on 2026-06-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('processors', 'Процесори'), ('gpu', 'Відеокарти'), ('ram', "Оперативна пам'ять"), ('mice', 'Ігрові миші'), ('keyboards', 'Клавіатури'), ('microphones', 'Мікрофони'), ('monitors', 'Монітори')], max_length=50, verbose_name='Категорія'),
        ),
    ]
