# Generated by Django 6.0.6 on 2026-06-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_brand_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.JSONField(default=dict, verbose_name='Характеристики (JSON)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cpu', 'Процесори'), ('gpu', 'Відеокарти'), ('ram', "Оперативна пам'ять"), ('mouse', 'Мишки'), ('keyboard', 'Клавіатури'), ('monitor', 'Монітори')], max_length=50, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Опис'),
        ),
    ]
