# Generated by Django 6.0.6 on 2026-06-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Custom', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('processors', 'Процесори'), ('gpu', 'Відеокарти'), ('ram', "Оперативна пам'ять"), ('mice', 'Миші'), ('keyboards', 'Клавіатури'), ('microphones', 'Мікрофони'), ('monitors', 'Монітори')], default='processors', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
